// Sample data for the application - all variables are attached to window object
window.posts = [
  {
    id: "1",
    username: "emily99",
    profilePic: "https://via.placeholder.com/40x40/ff6b9d/white?text=ER",
    event: "Linkin Park",
    eventId: "101",
    goingCount: 5,
    downToGoCount: 15,
    timestamp: "2h ago",
    isGoing: false,
    isDownToGo: true,
  },
  {
    id: "2",
    username: "musiclover22",
    profilePic: "https://via.placeholder.com/40x40/4ecdc4/white?text=AC",
    event: "Morgan Wallen",
    eventId: "105",
    goingCount: 12,
    downToGoCount: 8,
    timestamp: "3h ago",
    isGoing: true,
    isDownToGo: false,
  },
  {
    id: "3",
    username: "concertfan",
    profilePic: "https://via.placeholder.com/40x40/a8e6cf/333?text=JS",
    event: "Dua Lipa",
    eventId: "110",
    goingCount: 7,
    downToGoCount: 11,
    timestamp: "5h ago",
    isGoing: false,
    isDownToGo: true,
  },
  {
    id: "4",
    username: "emily99",
    profilePic: "https://via.placeholder.com/40x40/ff6b9d/white?text=ER",
    event: "Tate McRae",
    eventId: "107",
    goingCount: 9,
    downToGoCount: 6,
    timestamp: "1d ago",
    isGoing: true,
    isDownToGo: false,
  },
  {
    id: "5",
    username: "musiclover22",
    profilePic: "https://via.placeholder.com/40x40/4ecdc4/white?text=AC",
    event: "Benson Boone",
    eventId: "109",
    goingCount: 4,
    downToGoCount: 13,
    timestamp: "1d ago",
    isGoing: false,
    isDownToGo: true,
  },
]

window.userProfiles = {
  emily99: {
    username: "emily99",
    displayName: "Emily Rodriguez",
    bio: "Pop music enthusiast | Always down for a good show 🎵",
    profilePic: "https://via.placeholder.com/100x100/ff6b9d/white?text=ER",
    location: "Boston, MA",
    joinedDate: "March 2023",
    eventsGoing: [
      {
        id: "107",
        name: "Tate McRae",
        date: "August 26, 2025",
        venue: "TD Garden",
        image: "https://via.placeholder.com/300x200/667eea/white?text=Tate+McRae",
      },
    ],
    eventsDownToGo: [
      {
        id: "101",
        name: "Linkin Park",
        date: "August 1, 2025",
        venue: "TD Garden",
        image: "https://via.placeholder.com/300x200/f093fb/white?text=Linkin+Park",
      },
      {
        id: "110",
        name: "Dua Lipa",
        date: "September 9, 2025",
        venue: "TD Garden",
        image: "https://via.placeholder.com/300x200/4facfe/white?text=Dua+Lipa",
      },
    ],
  },
  musiclover22: {
    username: "musiclover22",
    displayName: "Alex Chen",
    bio: "Country & pop concerts are my thing | TD Garden regular",
    profilePic: "https://via.placeholder.com/100x100/4ecdc4/white?text=AC",
    location: "Cambridge, MA",
    joinedDate: "January 2023",
    eventsGoing: [
      {
        id: "105",
        name: "Morgan Wallen",
        date: "August 22, 2025",
        venue: "Gillette Stadium",
        image: "https://via.placeholder.com/300x200/fbbf24/white?text=Morgan+Wallen",
      },
    ],
    eventsDownToGo: [
      {
        id: "109",
        name: "Benson Boone",
        date: "September 2, 2025",
        venue: "TD Garden",
        image: "https://via.placeholder.com/300x200/34d399/white?text=Benson+Boone",
      },
    ],
  },
  concertfan: {
    username: "concertfan",
    displayName: "Jordan Smith",
    bio: "Live music addict | Been to 50+ shows this year 🎤",
    profilePic: "https://via.placeholder.com/100x100/a8e6cf/333?text=JS",
    location: "Somerville, MA",
    joinedDate: "June 2022",
    eventsGoing: [],
    eventsDownToGo: [
      {
        id: "110",
        name: "Dua Lipa",
        date: "September 9, 2025",
        venue: "TD Garden",
        image: "https://via.placeholder.com/300x200/4facfe/white?text=Dua+Lipa",
      },
    ],
  },
}

window.events = [
  {
    id: "101",
    name: "Linkin Park",
    date: "August 1, 2025",
    time: "8:00 PM",
    venue: "TD Garden",
    city: "Boston, MA",
    image: "https://via.placeholder.com/300x200/f093fb/white?text=Linkin+Park",
    category: "music",
    genre: "Rock",
    goingCount: 5,
    downToGoCount: 15,
  },
  {
    id: "102",
    name: "Megan Moroney",
    date: "August 1, 2025",
    time: "7:30 PM",
    venue: "Road Runner",
    city: "Boston, MA",
    image: "https://via.placeholder.com/300x200/f59e0b/white?text=Megan+Moroney",
    category: "music",
    genre: "Country",
    goingCount: 6,
    downToGoCount: 7,
  },
  {
    id: "105",
    name: "Morgan Wallen",
    date: "August 22, 2025",
    time: "7:00 PM",
    venue: "Gillette Stadium",
    city: "Foxborough, MA",
    image: "https://via.placeholder.com/300x200/fbbf24/white?text=Morgan+Wallen",
    category: "music",
    genre: "Country",
    goingCount: 12,
    downToGoCount: 8,
  },
  {
    id: "107",
    name: "Tate McRae",
    date: "August 26, 2025",
    time: "8:00 PM",
    venue: "TD Garden",
    city: "Boston, MA",
    image: "https://via.placeholder.com/300x200/667eea/white?text=Tate+McRae",
    category: "music",
    genre: "Pop",
    goingCount: 9,
    downToGoCount: 6,
  },
  {
    id: "109",
    name: "Benson Boone",
    date: "September 2, 2025",
    time: "8:00 PM",
    venue: "TD Garden",
    city: "Boston, MA",
    image: "https://via.placeholder.com/300x200/34d399/white?text=Benson+Boone",
    category: "music",
    genre: "Pop",
    goingCount: 4,
    downToGoCount: 13,
  },
  {
    id: "110",
    name: "Dua Lipa",
    date: "September 9, 2025",
    time: "8:00 PM",
    venue: "TD Garden",
    city: "Boston, MA",
    image: "https://via.placeholder.com/300x200/4facfe/white?text=Dua+Lipa",
    category: "music",
    genre: "Pop",
    goingCount: 7,
    downToGoCount: 11,
  },
]

window.seatingSections = [
  { id: "floor", name: "Floor", row: "GA" },
  { id: "s101", name: "Section 101", row: "A-G" },
  { id: "s102", name: "Section 102", row: "A-G" },
  { id: "s103", name: "Section 103", row: "A-G" },
  { id: "s104", name: "Section 104", row: "A-G" },
  { id: "s105", name: "Section 105", row: "A-G" },
  { id: "s201", name: "Section 201", row: "A-M" },
  { id: "s202", name: "Section 202", row: "A-M" },
  { id: "s203", name: "Section 203", row: "A-M" },
  { id: "s204", name: "Section 204", row: "A-M" },
  { id: "s205", name: "Section 205", row: "A-M" },
]

window.ticketProviders = [
  { id: "tp1", name: "Ticketmaster", url: "https://ticketmaster.com" },
  { id: "tp2", name: "StubHub", url: "https://stubhub.com" },
  { id: "tp3", name: "SeatGeek", url: "https://seatgeek.com" },
  { id: "tp4", name: "Gametime", url: "https://gametime.co" },
]

window.ticketPrices = {
  floor: {
    tp1: { price: 250.0, fees: 45.0, total: 295.0, url: "https://ticketmaster.com" },
    tp2: { price: 265.5, fees: 49.5, total: 315.0, url: "https://stubhub.com" },
    tp3: { price: 245.75, fees: 44.25, total: 290.0, url: "https://seatgeek.com" },
    tp4: { price: 240.0, fees: 40.0, total: 280.0, url: "https://gametime.co" },
  },
  s101: {
    tp1: { price: 150.0, fees: 25.0, total: 175.0, url: "https://ticketmaster.com" },
    tp2: { price: 145.5, fees: 24.5, total: 170.0, url: "https://stubhub.com" },
    tp3: { price: 155.75, fees: 29.25, total: 185.0, url: "https://seatgeek.com" },
    tp4: { price: 142.0, fees: 23.0, total: 165.0, url: "https://gametime.co" },
  },
  s102: {
    tp1: { price: 140.0, fees: 22.0, total: 162.0, url: "https://ticketmaster.com" },
    tp2: { price: 135.5, fees: 21.5, total: 157.0, url: "https://stubhub.com" },
    tp3: { price: 145.75, fees: 24.25, total: 170.0, url: "https://seatgeek.com" },
    tp4: { price: 132.0, fees: 20.0, total: 152.0, url: "https://gametime.co" },
  },
  s103: {
    tp1: { price: 135.0, fees: 21.0, total: 156.0, url: "https://ticketmaster.com" },
    tp2: { price: 130.5, fees: 20.5, total: 151.0, url: "https://stubhub.com" },
    tp3: { price: 140.75, fees: 23.25, total: 164.0, url: "https://seatgeek.com" },
    tp4: { price: 127.0, fees: 19.0, total: 146.0, url: "https://gametime.co" },
  },
  s104: {
    tp1: { price: 145.0, fees: 23.0, total: 168.0, url: "https://ticketmaster.com" },
    tp2: { price: 140.5, fees: 22.5, total: 163.0, url: "https://stubhub.com" },
    tp3: { price: 150.75, fees: 25.25, total: 176.0, url: "https://seatgeek.com" },
    tp4: { price: 137.0, fees: 21.0, total: 158.0, url: "https://gametime.co" },
  },
  s105: {
    tp1: { price: 155.0, fees: 26.0, total: 181.0, url: "https://ticketmaster.com" },
    tp2: { price: 150.5, fees: 25.5, total: 176.0, url: "https://stubhub.com" },
    tp3: { price: 160.75, fees: 28.25, total: 189.0, url: "https://seatgeek.com" },
    tp4: { price: 147.0, fees: 24.0, total: 171.0, url: "https://gametime.co" },
  },
  s201: {
    tp1: { price: 89.99, fees: 15.99, total: 105.98, url: "https://ticketmaster.com" },
    tp2: { price: 95.5, fees: 18.5, total: 114.0, url: "https://stubhub.com" },
    tp3: { price: 92.75, fees: 16.25, total: 109.0, url: "https://seatgeek.com" },
    tp4: { price: 85.0, fees: 14.0, total: 99.0, url: "https://gametime.co" },
  },
  s202: {
    tp1: { price: 85.0, fees: 15.0, total: 100.0, url: "https://ticketmaster.com" },
    tp2: { price: 89.5, fees: 15.5, total: 105.0, url: "https://stubhub.com" },
    tp3: { price: 82.75, fees: 12.25, total: 95.0, url: "https://seatgeek.com" },
    tp4: { price: 80.0, fees: 12.0, total: 92.0, url: "https://gametime.co" },
  },
  s203: {
    tp1: { price: 82.0, fees: 14.0, total: 96.0, url: "https://ticketmaster.com" },
    tp2: { price: 86.5, fees: 14.5, total: 101.0, url: "https://stubhub.com" },
    tp3: { price: 79.75, fees: 11.25, total: 91.0, url: "https://seatgeek.com" },
    tp4: { price: 77.0, fees: 11.0, total: 88.0, url: "https://gametime.co" },
  },
  s204: {
    tp1: { price: 88.0, fees: 15.0, total: 103.0, url: "https://ticketmaster.com" },
    tp2: { price: 92.5, fees: 16.5, total: 109.0, url: "https://stubhub.com" },
    tp3: { price: 85.75, fees: 13.25, total: 99.0, url: "https://seatgeek.com" },
    tp4: { price: 83.0, fees: 13.0, total: 96.0, url: "https://gametime.co" },
  },
  s205: {
    tp1: { price: 91.0, fees: 16.0, total: 107.0, url: "https://ticketmaster.com" },
    tp2: { price: 95.5, fees: 17.5, total: 113.0, url: "https://stubhub.com" },
    tp3: { price: 88.75, fees: 14.25, total: 103.0, url: "https://seatgeek.com" },
    tp4: { price: 86.0, fees: 14.0, total: 100.0, url: "https://gametime.co" },
  },
}

window.sampleUsers = {
  going: [
    { username: "emily99", profilePic: "https://via.placeholder.com/40x40/ff6b9d/white?text=ER" },
    { username: "musiclover22", profilePic: "https://via.placeholder.com/40x40/4ecdc4/white?text=AC" },
    { username: "concertfan", profilePic: "https://via.placeholder.com/40x40/a8e6cf/333?text=JS" },
    { username: "rockstar123", profilePic: "https://via.placeholder.com/40x40/ffd93d/333?text=RS" },
    { username: "popfan456", profilePic: "https://via.placeholder.com/40x40/ff9ff3/white?text=PF" },
    { username: "countrymusic", profilePic: "https://via.placeholder.com/40x40/74b9ff/white?text=CM" },
  ],
  downToGo: [
    { username: "livemusic99", profilePic: "https://via.placeholder.com/40x40/fd79a8/white?text=LM" },
    { username: "concertgoer", profilePic: "https://via.placeholder.com/40x40/00b894/white?text=CG" },
    { username: "musiclover", profilePic: "https://via.placeholder.com/40x40/e17055/white?text=ML" },
    { username: "showtime", profilePic: "https://via.placeholder.com/40x40/a29bfe/white?text=ST" },
  ],
}
